#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1565448491                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The highly addictive racing game

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Gustav Prüzelius
your_link                                 : https://gupr.net
your_city                                 : Stockholm
email_address                             : gustav@pruzelius.se
facebook_username                         :
instagram_username                        : gustavpru
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : High paced gameplay
    description                           : Get hooked with the games addictiveness
    fontawesome_icon_name                 : shipping-fast

  - title                                 : Intense driving and racing
    description                           : Fight to stay alive on the highway
    fontawesome_icon_name                 : car

  - title                                 : Leaderboards and achievements through Game Center
    description                           : Go up against friends to find out who's the best driver
    fontawesome_icon_name                 : trophy

  - title                                 : Satisfying controls and life-like car physics
    description                           : Feel a smooth driving experience
    fontawesome_icon_name                 : gamepad

  - title                                 : Unlocks and upgrades!
    description                           : Get new cars to level up your score
    fontawesome_icon_name                 : money-bill

  - title                                 : Simple but beautiful pixel art
    description                           : Get nostalgic from the graphics
    fontawesome_icon_name                 : heart

  - title                                 : Intuitive menus
    description                           : Become satisfied and nutty with smooth transitions
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ff5733 "

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#77dd77"
feature_text_color                        : "#77dd77"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#F7CAC9"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
